### ISSUE TITLE
What network are you using as an input?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/vbet#1]
One of the most fundamental inputs into VBET is the drainage network. Its extent controls:
- Where classic VBET (slope analysis within buffer from stream) looks
- Where new VBET waterbodies works (not just polygons, but bankfull buffer polygon)
The only part that doesn't get included is the version you run now is [HAND](https://github.com/dhardestylewis/HAND-TauDEM), but when we run HAND with our own inputs (e.g. NED and NHD), we need the **D** (i.e. drainage) specified as input.

There are some things to work out:
1. Which drainage are you using by default (I think it is NHD + HR)?
2. What extent of the drainage network (i.e. are you filtering by an FCODE of 46006 for perrenial?

I want 46003 (intermittent) and 46007 (intermittent) and you end up needing a lot of Artificial Path's too to get right network - @wally-mac will have insights on this).

Also, that critical input is not part of current business logic. @joewheaton will fix.

![](https://lh3.googleusercontent.com/-Cw8hO-g7JHQ/Xp-F7Yx5kFI/AAAAAAACtQk/4m8d0ojixjQei0MTNRZ-BslyqZb5LodYQCK8BGAsYHg/s0/2020-04-21.png)

**Comment by philipbaileynar** [comment]
We are indeed using NHDPlusHR (the latest and great 1:24K). I will make sure that we are retaining intermittent (46003) and ephemeral streams (46007). I don't think the original VBET was retaining ephemeral though. @wally-mac can confirm.

Artificial paths should be moot because we are burning flow area and waterbody polygons into the channel mask raster. Then incorporating the NHD network (perennial for sure, and soon to be confirmed intermittent and ephemeral).

**Comment by joewheaton** [comment]
Thanks... we should roll up our sleeves on this next week and dial in our approach.

**Comment by joewheaton** [comment]
@wally-mac or @mhallerud please chime in with clarification of what we do in pyBRAT. 

@philipbaileynar I think they are going to say they do everything, but they also include canals. We want what pyBRAT uses, but not canals. 

I particularly need these re-run for Middle Bear VBET.

**Comment by mhallerud** [comment]
@philipbaileynar @joewheaton We use the full NHD 24k flowline for pyBRAT, removing pipelines, coastlines, and underground conduits. For the final products we clip down to the perennial plus canals, as defined by the [perennial network script](https://github.com/Riverscapes/pyBRAT/blob/master/SupportingTools/perennialNetwork.py).

**Comment by philipbaileynar** [comment]
In BRAT, I have implemented (but not pushed) the FCode filtering described by @mhallerud . I will implement the same filtering in VBET. Easy. I will close this issue when it is done.

**Comment by philipbaileynar** [comment]
Closing because this has been superseded by #19

**Comment by joewheaton** [comment]
@philipbaileynar sorry to be a pesk...  just to clarify, when you say you 

> I have implemented (but not pushed) the FCode filtering

please tell me you mean:

> the full NHD 24k flowline for pyBRAT, removing pipelines, coastlines, and underground conduits.

i.e. keep everything but: pipelines (42800 throuh 42816), coastlines (56600)? 

Please note that the perennial network script Sara made is only at the end for final products they display.

**Comment by philipbaileynar** [comment]
When we run BRAT we now pass the following as one of the command line arguments:

```
--reach_codes 33400,33600,33601,33603,46000,46003,46006,46007,55800
```

This is the list of FCodes that are **retained** for the BRAT run. Dam capacity and all other output values are calculated for all retained reaches. Users can then filter to perennial, intermittent etc when they view the results.

We will implement the same `reach_codes` parameter for VBET and pass the same list of reach codes when we run VBET. Obviously works a little differently because it's not a reach scale model and the retention of reaches will result in polygons that extend further up valleys etc.

**Comment by philipbaileynar** [comment]
Also, I should have pointed out from the very first post... "check the log file".

From an old BRAT log file before the new reach code filtering was implemented:

```
2020-04-24 13:51:31,930 INFO     [Build Network  ] Building network from flow lines /Users/philip/GISData/BRAT/brat/17060103/inputs/NHDFlowline.shp
2020-04-24 13:51:31,931 INFO     [Build Network  ] Retaining intermittent reaches with code 46003
2020-04-24 13:51:31,931 INFO     [Build Network  ] Retaining perennial reaches with code 46006
2020-04-24 13:51:41,220 INFO     [Build Network  ] Retaining artificial features within waterbody features smaller than 10000.0km2

```

From a recent version of VBET:

```
2020-04-17 19:14:55,482 INFO     [VBET Network   ] Generating perennial network
2020-04-17 19:14:55,484 INFO     [VBET Network   ] Incorporating perennial features
2020-04-17 19:14:57,945 INFO     [VBET Network   ] Incorporating flow areas.
```

These are old log statements that don't reflect the latest code... but we always try to incorporate this type of transparency in the log files.

**Comment by joewheaton** [comment]
Super helpful! I like the log files...
