### ISSUE TITLE
Help me understand what Slope Evidence is

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/vbet#17]
I get that the purpose of [normalizing the slope input](https://riverscapes.github.io/vbet/algorithm.html#step-1---slope-evidence) into 0 - 1 is to make it easier to combine multiple lines of evidence.  

> The goal is to invert the raster so that low slope values have the highest raster values and then discard (set null) any areas that had an original slope value of 12 degrees or greater. 

I also get that we can display that intermediate like below (#16):

![image](https://user-images.githubusercontent.com/9723905/81016063-fe021800-8e1c-11ea-9056-903a26ff24cf.png)

However, I am confused on *why* you did exactly this:

> The first step is to divide the original slope raster by -12 and then add 1. We then set any negative values to NULL. ([code](https://github.com/Riverscapes/sqlBRAT/blob/master/vbet.py#L144-L145)). The constant value of 12 is passed to the script as an argument so that it can be adjusted easily.

1. Why 12? I get the negative (to invert it). Is 12 degrees an arbitrary or informed cut-off? 
2. Is it something that requires user judgement? Calibration? 
3. Is exposing that knob significant? 
4. I take it this only works when the range is well defined (i.e. works for degrees slope upto 90 but not for percent slope)?

**Comment by philipbaileynar** [comment]
The intent is to discard high slope that has no chance of being valley bottom.

If we simply rescaled slope degrees (0-90) down to zero to one (0-1) essentially each 10 degree of slope would occupy 0.1 of the range in the transformed evidence raster.

Instead we discard slope greater than 12 degrees (the old VBET maximum) and spread 0-12 over the output range (0-1). Now ever one degree of slope occupies the 0.1 range in the output.

This isn't a big deal when you have just one line of evidence. But when you are multiplying multiple lines of zero to one rasters together you get the most descriptive range of outputs if your inputs are not condensed over a very small range of values.

As mentioned above, the value of 12 was chosen because it was the old max valley bottom slope in the old VBET. I leave the value of 12 exposed so that others can choose their own max eligible slope. I don't think people will need to change this (much like the 300 m segmentation length in BRAT).

**Comment by philipbaileynar** [comment]
Also, the 12 degree cut off isn't totally necessary with a fixed scale values like slope. But with HAND we need to know over what range of HAND to scale zero to one. Should HAND of 100 be evidence 0, or should HAND of 1000 be 0? 

I used the same approach for both lines of evidence to make it consistent.

**Comment by joewheaton** [comment]
Interesting... this is key:

> we discard slope greater than 12 degrees (the old VBET maximum) and spread 0-12 over the output range (0-1). Now ever one degree of slope occupies the 0.1 range in the output.

This all works. Same as #18, should we adjust this as function of drainage area?

**Comment by philipbaileynar** [comment]
See my response on #18 

Please close this issue when satisfied.
