### ISSUE TITLE
Help me understand HAND normaliztion?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/vbet#18]
I get that the purpose of [normalizing the HAND input](riverscapes.github.io/vbet/algorithm.html#step-2---hand-evidence) into 0 - 1 is to make it easier to combine multiple lines of evidence.  

> The goal is to invert the raster so that high HAND values have the lowest raster values and then discard and values greater than 50 m.

I also get that we can display that intermediate like below (#16):

![image](https://user-images.githubusercontent.com/9723905/81016212-3c97d280-8e1d-11ea-974e-b84a97f0baee.png)

However, I am confused on *why* you did exactly this:

> It is divided by -50 and then 1 added to the result. (code). Again the constant value of 50 is passed as an argument.

1. Why 50? I get the negative (to invert it). Is 50 meters an arbitrary or informed cut-off? It seems like this should be a function of drainage area.
2. Is it something that requires user judgement? Calibration? 
3. Is exposing that knob significant? Here you hint 50 is an argument.

**Comment by philipbaileynar** [comment]
See explanation for #17 

In the case of HAND... 50 was a completely arbitrary number!!!! I closed my eyes and pictured a valley and considered all remnant terraces and other valley bottom artifacts to be within 50 m vertically of the channel.

I expect others to have a more evidence based approach to determining this value. But again, this is just the upper limit of possible valley bottom. HAND of 50 m becomes evidence = 0.

**Comment by joewheaton** [comment]
Okay thanks. So:
1. Where does it get exposed to user specifically?
2. What do you think about my question of whether or not it should be attempted as a function of drainage area? Either as a VBET 1.0 kind of thing where just three values for small, medium and large drainage areas (I kind of like this) or as a continuous function.

**Comment by philipbaileynar** [comment]
It gets exposed on the command line when you run VBET. See default value at end of line.

https://github.com/Riverscapes/sqlBRAT/blob/master/vbet.py#L330

You know me... I want to avoid scale dependent values wherever possible. I can tolerate the bankfull width buffer algorithm relying on drainage area because NHD comes with a drainage area attribute. This is currently the only use of drainage area in the whole of VBET and it's fine because it's a vector use relying on a vector attribute. Introducing drainage area to the evidence rasters feels like a step backward.

**Comment by joewheaton** [comment]
Thanks @philipbaileynar. I think we should test outputs of VBET for a bit before deciding. If it works like we have it, then we can move on...
